//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharp_API_TestFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public bool isActive { get; set; }

        public bool stEquals(Student st)
        {
            return this.StudentId == st.StudentId &&
                    this.Email == st.Email &&
                    this.FirstName == st.FirstName &&
                    this.LastName == st.LastName &&
                    this.Phone == st.Phone &&
                    this.isActive == st.isActive;
        }
    }
}
